# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '3b638e2495ee6bfc3c74cc9b8b909872'
  config.secret_key = '87b120c4983572537060b1afdc5b54b0'
  config.default_from = 'no_reply@reagency-mada.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
